# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.12

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake

# The command to remove a file.
RM = /Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/luke/CLionProjects/371LastProject

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/luke/CLionProjects/371LastProject/cmake-build-debug

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/Applications/CLion.app/Contents/bin/cmake/mac/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/luke/CLionProjects/371LastProject/cmake-build-debug/CMakeFiles /Users/luke/CLionProjects/371LastProject/cmake-build-debug/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/luke/CLionProjects/371LastProject/cmake-build-debug/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named 371LastProject

# Build rule for target.
371LastProject: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 371LastProject
.PHONY : 371LastProject

# fast build rule for target.
371LastProject/fast:
	$(MAKE) -f CMakeFiles/371LastProject.dir/build.make CMakeFiles/371LastProject.dir/build
.PHONY : 371LastProject/fast

lc3.o: lc3.c.o

.PHONY : lc3.o

# target to build an object file
lc3.c.o:
	$(MAKE) -f CMakeFiles/371LastProject.dir/build.make CMakeFiles/371LastProject.dir/lc3.c.o
.PHONY : lc3.c.o

lc3.i: lc3.c.i

.PHONY : lc3.i

# target to preprocess a source file
lc3.c.i:
	$(MAKE) -f CMakeFiles/371LastProject.dir/build.make CMakeFiles/371LastProject.dir/lc3.c.i
.PHONY : lc3.c.i

lc3.s: lc3.c.s

.PHONY : lc3.s

# target to generate assembly for a file
lc3.c.s:
	$(MAKE) -f CMakeFiles/371LastProject.dir/build.make CMakeFiles/371LastProject.dir/lc3.c.s
.PHONY : lc3.c.s

lc3ui.o: lc3ui.c.o

.PHONY : lc3ui.o

# target to build an object file
lc3ui.c.o:
	$(MAKE) -f CMakeFiles/371LastProject.dir/build.make CMakeFiles/371LastProject.dir/lc3ui.c.o
.PHONY : lc3ui.c.o

lc3ui.i: lc3ui.c.i

.PHONY : lc3ui.i

# target to preprocess a source file
lc3ui.c.i:
	$(MAKE) -f CMakeFiles/371LastProject.dir/build.make CMakeFiles/371LastProject.dir/lc3ui.c.i
.PHONY : lc3ui.c.i

lc3ui.s: lc3ui.c.s

.PHONY : lc3ui.s

# target to generate assembly for a file
lc3ui.c.s:
	$(MAKE) -f CMakeFiles/371LastProject.dir/build.make CMakeFiles/371LastProject.dir/lc3ui.c.s
.PHONY : lc3ui.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... 371LastProject"
	@echo "... lc3.o"
	@echo "... lc3.i"
	@echo "... lc3.s"
	@echo "... lc3ui.o"
	@echo "... lc3ui.i"
	@echo "... lc3ui.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

